# Your app/website name
name = 'spc'
# slqite db URI
db = 'spc.db' 
# sled db URI
sled = 'spc.sled'
# listen address
addr = '127.0.0.1:8080'
# upload icons here
icons_path = './data/icons' 
# store avatar imgs here
avatars_path = './data/avatars'
# upload folder
upload_path = './data/upload' 
# serve static folder, like SPA assets
serve_dir = [["app", "./dist"], ["assets", "./dist/assets"]]
# for JWT
secret_key = "pL3AsG1v3AharDk3y"
# to enable https
cert = ''
key = ''
# default admin name, !IMPORTANT!
admin_name = 'goodman'
# if process images on uploading
if_compress_img = true 
# set the inactivive interval to clean up on collaborative writing
expiry_hours = 12 
