name = 'spc'
db = 'spc.db'
sled = 'spc.sled'
addr = '127.0.0.1:3001'
avatars_path = './data/imgs/avatars'
upload_path = './data/upload'
serve_dir = [["mdpad", "./dist"], ["assets", "./dist/assets"]]
secret_key = "pL3AsG1v3AharDk3y"
cert = ''
key = ''
admin_name = 'goodman'
if_compress_img = true
expiry_hours = 12 
