name: Test

on:
  workflow_dispatch:
      
jobs:
  cargo:
    name: Cargo test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
          components: clippy, rustfmt
      
      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo test
        run: cargo test
